# Generated by Django 6.0.2 on 2026-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EmployeeId", models.IntegerField()),
                ("EmployeeName", models.CharField(max_length=200)),
                ("Designation", models.CharField(max_length=150)),
                ("gender", models.CharField(max_length=100)),
                ("Address", models.CharField(max_length=200)),
            ],
        ),
    ]
